/**
 * AYUSH Dashavidha Pariksha — 10-fold examination question bank
 * Based on Ashtanga Hridayam and standard Ayurvedic clinical texts.
 * Each question: multilingual (en + hi), options, and ayush_field mapping.
 *
 * NOTE: These questions should be validated by a licensed AYUSH physician.
 * clinician_validated: false — awaiting clinical review.
 */

export const DASHAVIDHA_QUESTIONS = [
  {
    id: 'prakriti',
    step: 1,
    category: 'Prakriti',
    category_hi: 'प्रकृति',
    description_en: 'Body Constitution — Vata, Pitta, or Kapha dominance',
    description_hi: 'शारीरिक प्रकृति — वात, पित्त या कफ की प्रधानता',
    question_en: 'How would you describe your natural body build and energy level from childhood?',
    question_hi: 'बचपन से आपका स्वभाव और शरीर की प्रकृति कैसी रही है?',
    options: [
      { label_en: 'Thin, restless, creative — variable energy',     label_hi: 'पतला, चंचल, रचनात्मक — ऊर्जा अस्थिर',      value: 'vata' },
      { label_en: 'Medium build, sharp, goal-oriented — intense',   label_hi: 'मध्यम काया, तीक्ष्ण, लक्ष्य-केंद्रित — तीव्र', value: 'pitta' },
      { label_en: 'Heavy, calm, steady — strong endurance',         label_hi: 'भारी, शांत, स्थिर — मजबूत सहनशक्ति',        value: 'kapha' },
      { label_en: 'Mixed — a combination of the above',             label_hi: 'मिश्रित — उपरोक्त का संयोजन',                value: 'mixed' },
    ],
    ayush_field: 'prakriti_dosha',
    clinician_validated: false,
  },
  {
    id: 'vikriti',
    step: 2,
    category: 'Vikriti',
    category_hi: 'विकृति',
    description_en: 'Current Imbalance — deviation from natural constitution',
    description_hi: 'वर्तमान विकृति — स्वाभाविक प्रकृति से विचलन',
    question_en: 'Which of these best describes your current complaints?',
    question_hi: 'इनमें से कौन सा आपकी वर्तमान शिकायत को सबसे अच्छे से बताता है?',
    options: [
      { label_en: 'Dryness, constipation, joint pain, anxiety',     label_hi: 'रूखापन, कब्ज, जोड़ों का दर्द, बेचैनी',  value: 'vata_vikriti' },
      { label_en: 'Acidity, inflammation, skin rash, irritability', label_hi: 'एसिडिटी, सूजन, त्वचा पर दाने, चिड़चिड़ापन', value: 'pitta_vikriti' },
      { label_en: 'Congestion, weight gain, heaviness, sluggishness',label_hi: 'कफ जमना, वजन बढ़ना, भारीपन, आलस्य',         value: 'kapha_vikriti' },
      { label_en: 'None of the above / I feel balanced',            label_hi: 'उपरोक्त में से कोई नहीं / मैं संतुलित महसूस करता हूँ', value: 'balanced' },
    ],
    ayush_field: 'vikriti',
    clinician_validated: false,
  },
  {
    id: 'sara',
    step: 3,
    category: 'Sara',
    category_hi: 'सार',
    description_en: 'Tissue Quality — excellence of bodily tissues',
    description_hi: 'धातु सार — शारीरिक ऊतकों की उत्कृष्टता',
    question_en: 'How is your skin and hair quality generally?',
    question_hi: 'आपकी त्वचा और बालों की गुणवत्ता सामान्यतः कैसी है?',
    options: [
      { label_en: 'Dry, rough skin; thin, brittle hair',     label_hi: 'रूखी, खुरदरी त्वचा; पतले, भंगुर बाल',      value: 'vata_sara' },
      { label_en: 'Oily, sensitive skin; moderate hair loss', label_hi: 'तैलीय, संवेदनशील त्वचा; सामान्य बाल झड़ना', value: 'pitta_sara' },
      { label_en: 'Soft, moist skin; thick, lustrous hair',   label_hi: 'मुलायम, आर्द्र त्वचा; घने, चमकदार बाल',   value: 'kapha_sara' },
    ],
    ayush_field: 'sara',
    clinician_validated: false,
  },
  {
    id: 'samhanana',
    step: 4,
    category: 'Samhanana',
    category_hi: 'संहनन',
    description_en: 'Body Build — compactness and structure of the body',
    description_hi: 'शारीरिक संरचना — शरीर की दृढ़ता और बनावट',
    question_en: 'How would you describe your overall body frame and muscle tone?',
    question_hi: 'आप अपने शरीर की बनावट और मांसपेशियों को कैसे वर्णित करेंगे?',
    options: [
      { label_en: 'Lean, light — bones visible, low muscle mass', label_hi: 'दुबला-पतला — हड्डियाँ दिखती हैं, कम मांसपेशियाँ', value: 'lean' },
      { label_en: 'Medium — proportionate, moderate muscles',     label_hi: 'मध्यम — संतुलित, मध्यम मांसपेशियाँ',              value: 'medium' },
      { label_en: 'Heavy/stocky — well-built, thick muscles',     label_hi: 'भारी/मजबूत — सुगठित, मोटी मांसपेशियाँ',         value: 'heavy' },
    ],
    ayush_field: 'samhanana',
    clinician_validated: false,
  },
  {
    id: 'pramana',
    step: 5,
    category: 'Pramana',
    category_hi: 'प्रमाण',
    description_en: 'Body Measurement — proportionality of bodily organs',
    description_hi: 'शारीरिक माप — अंगों की समानुपातिकता',
    question_en: 'Compared to others your age, how is your body height and weight?',
    question_hi: 'अपनी उम्र के लोगों की तुलना में आपकी ऊँचाई और वजन कैसा है?',
    options: [
      { label_en: 'Shorter or thinner than average',  label_hi: 'औसत से छोटा या पतला',     value: 'below_avg' },
      { label_en: 'About average for my age and sex', label_hi: 'मेरी उम्र और लिंग के लिए औसत', value: 'average' },
      { label_en: 'Taller or heavier than average',   label_hi: 'औसत से लंबा या भारी',       value: 'above_avg' },
    ],
    ayush_field: 'pramana',
    clinician_validated: false,
  },
  {
    id: 'satmya',
    step: 6,
    category: 'Satmya',
    category_hi: 'सात्म्य',
    description_en: 'Dietary Suitability — what the body is accustomed to',
    description_hi: 'आहार सात्म्य — शरीर किन खाद्य पदार्थों का अभ्यस्त है',
    question_en: 'Which type of diet have you followed most of your life?',
    question_hi: 'आपने अपने जीवन में अधिकतर किस प्रकार का आहार लिया है?',
    options: [
      { label_en: 'Vegetarian (no meat, eggs)',          label_hi: 'शाकाहारी (मांस, अंडे नहीं)',            value: 'vegetarian' },
      { label_en: 'Vegetarian + dairy (lacto-veg)',       label_hi: 'शाकाहारी + डेयरी (लैक्टो-शाकाहारी)',  value: 'lacto_veg' },
      { label_en: 'Non-vegetarian (meat, fish, eggs)',   label_hi: 'मांसाहारी (मांस, मछली, अंडे)',         value: 'non_veg' },
      { label_en: 'Mixed / varies by season or region',  label_hi: 'मिश्रित / मौसम या क्षेत्र के अनुसार', value: 'mixed' },
    ],
    ayush_field: 'satmya',
    clinician_validated: false,
  },
  {
    id: 'sattva',
    step: 7,
    category: 'Sattva',
    category_hi: 'सत्त्व',
    description_en: 'Mental Strength — emotional resilience and clarity of mind',
    description_hi: 'मानसिक बल — भावनात्मक दृढ़ता और मन की स्पष्टता',
    question_en: 'How do you generally handle stress, illness, or difficult situations?',
    question_hi: 'आप सामान्यतः तनाव, बीमारी या कठिन परिस्थितियों को कैसे संभालते हैं?',
    options: [
      { label_en: 'Strong — I stay calm and recover quickly',       label_hi: 'मजबूत — मैं शांत रहता हूँ और जल्दी ठीक हो जाता हूँ',      value: 'sattvic' },
      { label_en: 'Moderate — I manage but feel stressed at times', label_hi: 'मध्यम — मैं संभाल लेता हूँ लेकिन कभी-कभी तनाव महसूस होता है', value: 'rajasic' },
      { label_en: 'Low — I easily feel overwhelmed or depressed',   label_hi: 'कम — मैं आसानी से अभिभूत या उदास महसूस करता हूँ',           value: 'tamasic' },
    ],
    ayush_field: 'sattva',
    clinician_validated: false,
  },
  {
    id: 'ahara_shakti',
    step: 8,
    category: 'Ahara Shakti',
    category_hi: 'आहार शक्ति',
    description_en: 'Digestive Capacity — strength of digestion and appetite',
    description_hi: 'पाचन शक्ति — पाचन की क्षमता और भूख',
    question_en: 'How is your appetite and digestion normally?',
    question_hi: 'आपकी भूख और पाचन सामान्यतः कैसी है?',
    options: [
      { label_en: 'Variable — sometimes very hungry, sometimes no appetite; bloating common', label_hi: 'अनियमित — कभी बहुत भूख, कभी बिल्कुल नहीं; अफारा सामान्य', value: 'variable' },
      { label_en: 'Sharp — strong hunger, irritable if meals are late',                       label_hi: 'तीव्र — तेज भूख, देर होने पर चिड़चिड़ापन',                  value: 'sharp' },
      { label_en: 'Slow — low appetite, feel full quickly, digestion is sluggish',            label_hi: 'धीमी — कम भूख, जल्दी भर जाना, पाचन सुस्त',                value: 'slow' },
      { label_en: 'Normal — eat well, digest comfortably',                                    label_hi: 'सामान्य — अच्छी भूख, आराम से पचता है',                      value: 'normal' },
    ],
    ayush_field: 'ahara_shakti',
    clinician_validated: false,
  },
  {
    id: 'vyayama_shakti',
    step: 9,
    category: 'Vyayama Shakti',
    category_hi: 'व्यायाम शक्ति',
    description_en: 'Exercise Capacity — physical endurance and stamina',
    description_hi: 'व्यायाम क्षमता — शारीरिक सहनशक्ति',
    question_en: 'How is your physical stamina for daily activities or exercise?',
    question_hi: 'दैनिक कार्यों या व्यायाम के लिए आपकी शारीरिक क्षमता कैसी है?',
    options: [
      { label_en: 'Low — tire easily, prefer light activity',         label_hi: 'कम — जल्दी थक जाता हूँ, हल्की गतिविधि पसंद',    value: 'low' },
      { label_en: 'Moderate — can walk/work but dislike intense exercise', label_hi: 'मध्यम — चल-फिर सकता हूँ लेकिन तीव्र व्यायाम पसंद नहीं', value: 'moderate' },
      { label_en: 'High — active lifestyle, enjoy vigorous exercise', label_hi: 'अधिक — सक्रिय जीवनशैली, तीव्र व्यायाम पसंद',    value: 'high' },
    ],
    ayush_field: 'vyayama_shakti',
    clinician_validated: false,
  },
  {
    id: 'vaya',
    step: 10,
    category: 'Vaya',
    category_hi: 'वय',
    description_en: 'Age Assessment — stage of life for contextual diagnosis',
    description_hi: 'वय — जीवन की अवस्था का संदर्भ-आधारित निदान',
    question_en: 'Which life stage do you feel you are currently in?',
    question_hi: 'आप वर्तमान में जीवन की किस अवस्था में हैं?',
    options: [
      { label_en: 'Childhood / Adolescence (under 20)',    label_hi: 'बाल्यावस्था / किशोरावस्था (20 से कम)',   value: 'bala' },
      { label_en: 'Young Adult (20–40)',                   label_hi: 'युवा (20–40)',                             value: 'madhyama' },
      { label_en: 'Middle Age (40–60)',                    label_hi: 'प्रौढ़ावस्था (40–60)',                    value: 'prauda' },
      { label_en: 'Senior / Elderly (above 60)',           label_hi: 'वृद्धावस्था (60 से अधिक)',               value: 'vriddha' },
    ],
    ayush_field: 'vaya',
    clinician_validated: false,
  },
];

// Ahara-Vihara supplementary questions
export const AHARA_VIHARA_QUESTIONS = [
  {
    id: 'sleep',
    question_en: 'How many hours do you sleep at night on average?',
    question_hi: 'आप रात में औसतन कितने घंटे सोते हैं?',
    options: [
      { label_en: 'Less than 5 hours', label_hi: '5 घंटे से कम', value: '<5' },
      { label_en: '5–6 hours',         label_hi: '5–6 घंटे',      value: '5-6' },
      { label_en: '7–8 hours',         label_hi: '7–8 घंटे',      value: '7-8' },
      { label_en: 'More than 8 hours', label_hi: '8 घंटे से अधिक', value: '>8' },
    ],
    ayush_field: 'nidra',
  },
  {
    id: 'bowel',
    question_en: 'How is your bowel movement (Koshtha / stool passage)?',
    question_hi: 'आपका मलत्याग (कोष्ठ) कैसा है?',
    options: [
      { label_en: 'Hard stool, constipation, infrequent',        label_hi: 'कठोर मल, कब्ज, अनियमित',           value: 'krura' },
      { label_en: 'Loose stool, 2–3 times/day, sometimes urgency', label_hi: 'ढीला मल, दिन में 2–3 बार, कभी-कभी जल्दी', value: 'mridu' },
      { label_en: 'Normal — once or twice daily, comfortable',   label_hi: 'सामान्य — दिन में 1–2 बार, आरामदेह', value: 'madhyama' },
    ],
    ayush_field: 'koshtha',
  },
];

export default DASHAVIDHA_QUESTIONS;
